version: "3.9"
services:
  server:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
      - frontend
      - backend
    volumes:
      - ./server/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./server/nginx/ssl:/etc/nginx/ssl
      - ./server/nginx/logs:/etc/nginx/logs
    links:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "3001:3001"
